### ISSUE TITLE
Trying on RCX3 GPS data not detected

### ISSUE THREAD

**Issue by mathieubossaert** [purpledot/polar-rcx5-datalink#1]
Good morning,
thanks for that work which will keep living a lot of great rcx watches after the end of polar personnal trainer.
I try it over my rcx3 and I face an issue. bin and json export work but tcx does not : **2018-11-25T10:02:41 has no GPS data**
But it does, from a G5 GPS. I attached the bin and raw exported files
[20181125T100241.zip](https://github.com/purpledot/polar-rcx5-datalink/files/2682612/20181125T100241.zip)

Thanks again.

**Comment by purpledot** [comment]
Hi, thank you for the feedback.

It's probably because RCX3 has different protocol. At least boolean flags for status of HR transmitter and GPS sensor have different positions in bytearray. It's hard to tell more without .hrm and .gpx files.

**Comment by mathieubossaert** [comment]
Thanks. I Can get it from personnal trainer portal but is that what you should need ?

**Comment by mathieubossaert** [comment]
I found how to do it. I'll get thoses files later from a windows computer.
https://support.polar.com/au-en/support/tips/Data_Export_from_RCX5_CS500_to_ProTrainer_5

**Comment by mathieubossaert** [comment]
Here they are for two sessions.
[polar.zip](https://github.com/purpledot/polar-rcx5-datalink/files/2687263/polar.zip)

Thanks a lot !

**Comment by purpledot** [comment]
In short, you can't use this tool with your watch, but it shouldn't be too hard to make it work. 
Looks like the protocol is the same with some additional data here and there.

**Comment by mathieubossaert** [comment]
ok thanks, i will have a deeper look to your work.
