### ISSUE TITLE
"Insufficient permissions" error on Mac

### ISSUE THREAD

**Issue by JWJoubert** [purpledot/polar-rcx5-datalink#10]
Hi, does anyone maybe have advice. I am trying to run `rcx5 export` using python 3.8.2:

* I manually installed `libusb 1.0.21` (as suggested), from source using `configure && make && make install`. The `brew install libusb` unfortunately installs 1.0.23, so I uninstalled it.

While I get a similar error trace as #8, my trace ends with
```
 ...
  File "/Users/jwjoubert/.pyenv/versions/3.8.2/lib/python3.8/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/Users/jwjoubert/.pyenv/versions/3.8.2/lib/python3.8/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
```

Any advice, please? I'm attaching the whole error log too.
[error.log](https://github.com/purpledot/polar-rcx5-datalink/files/4603984/error.log)

I did try `sudo rcx5 export`, but to no avail.

**Comment by JWJoubert** [comment]
Let me close this issue as I will not be able to solve it. It seems that my DataLink USB device is faulty as I cannot connect it, even with the (newest) WebSync software.

**Comment by JakubkoM88** [comment]
Hi, before you throw away your Datalink USB try to find some old version of WebSync. I had also problem with latest version. Rcx5 is no longer supported by polar so maybe websync is now blocking connection... With older version of websync you can still download data to computer.

**Comment by JWJoubert** [comment]
Much appreciated @JakubkoM88 - I will definitely try it and report back.

**Comment by JWJoubert** [comment]
> Much appreciated @JakubkoM88 - I will definitely try it and report back.

@JakubkoM88 that was great advice, thanks. Working on an older Macbook (High Sierra) and WebSync 2.9.0 allows me to a) connect to the RCX5, and b) download the training files as `hrm` type files. 

So, I started the process all over again, making sure to install python 3.7.3 and libusb 1.0.21... but, still no joy. Still getting the dreaded error.
```
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
```

**Comment by JakubkoM88** [comment]
I got rcx5 this year from friend and also tryed to run this solution. I am not sure but maybe with the same result. Something with permissions. But i only want to upload activities to strava and this can be done with gpx and hrm data from websync(converted to tcx file).

**Comment by JWJoubert** [comment]
Indeed, thanks @JakubkoM88. I also, eventually, manually converted the `hrm` files using an [online tool](https://polarconverter.com) en then importing it into Strava. If you have another tool you can recommend, that would be appreciated, but I am now closing this issue and moving on.
