### ISSUE TITLE
polarpersonaltrainer.com ended

### ISSUE THREAD

**Issue by h4nc** [purpledot/polar-rcx5-datalink#2]
@purpledot
I found your project searching for possibilities to use my CS500 after polar ends the service.

Will your project still work after they shut down their servers.

Polar-rcx5-datalink ... will this also work with two CS500?

**Comment by purpledot** [comment]
> Will your project still work after they shut down their servers.

Yes. It has nothing to do with any Polar services.

> will this also work with two CS500?

Most likely no since CS500 has a different protocol. Even RCX3 (RCX5's sibling model) won't work without certain changes (https://github.com/purpledot/polar-rcx5-datalink/issues/1).

**Comment by h4nc** [comment]
Would it be possible to work this out for other devices. I think there are several people looking for something like this.

How did you reverse engineer the protocol. Is this possible for noobs like me?

**Comment by purpledot** [comment]
> Would it be possible to work this out for other devices

Yes.

> How did you reverse engineer the protocol.

[Wireshark](https://www.wireshark.org) helped to figure out how to connect the watch and export encoded training sessions. Then you take .hrm and .gpx files of these sessions (https://support.polar.com/au-en/support/tips/Data_Export_from_RCX5_CS500_to_ProTrainer_5) and try to make sense of the binary data you have exported.

> Is this possible for noobs like me?

Before this project I had no idea how this whole thing works. So I would say yes, it is possible.

**Comment by h4nc** [comment]
Unfortunately the link to wireshark isn’t valid or is it a user on git?

So where should I start?

**Comment by purpledot** [comment]
I've edited the link, it should work now.

> So where should I start?

Lean how to reverse engineer usb devices in general. Then try to understand how this software works.

On a side note, did you consider converting .hrm and .gpx files using services like [polarconverter](https://polarconverter.com/) and [upload](https://www.strava.com/upload/select) them to your Strava account?

**Comment by h4nc** [comment]
The goal would be to have it at some online service. I don’t have a strava account right now.
I just want to keep the ability to pull the data from my device, because it looks like polar won’t give us something to use the data locally.

Edit: I heard from those hrm and gpx giles the first time now.

So yes uploading to strava would be ok for me.

**Comment by purpledot** [comment]
Then you definitely should try it first.

1) [Export](https://support.polar.com/au-en/support/tips/Data_Export_from_RCX5_CS500_to_ProTrainer_5) .hrm and .gpx files.
2) [Convert](https://polarconverter.com/) them into .tcx files.
3) [Upload](https://www.strava.com/upload/select) to your Strava account.

**Comment by h4nc** [comment]
Ok, so I tried those steps and it worked.

The CS500 only exports a .hrm file because it has no gps. 

Is the software websync still needed with your project. I didn't get that yet. 
Or is it a stand alone thing.

Best thing would be to install this project on raspberry pi zero w and plud the datalink in and have everythin automated. Is this possible?
Or do we have to export the files from polar every time manually?

**Comment by purpledot** [comment]
> Is the software websync still needed with your project.

No you only need your watch and the [DataLink](https://support.polar.com/en/support/tips/Polar_DataLink).

> Best thing would be to install this project on raspberry pi zero w and plud the datalink in and have everythin automated.

Not sure about that since a have no experience with Raspberry Pi. But I think it is possible.

> Or do we have to export the files from polar every time manually?

No you don't need to do that.

**Comment by h4nc** [comment]
@purpledot did you already hear from this one, I found this on a [german page](https://gpsradler.de/news/polarpersonaltrainer-portal-eingestellt/) about the ending of polarpersonaltrainer.com

https://www.polar.com/accesslink-api/

EDIT: I don't know if this is only about Flowlink and not Datalink

**Comment by purpledot** [comment]
Yeah I know about it. Didn't find it useful.

**Comment by h4nc** [comment]
@purpledot can you point me in some direction on how you analysed the output of wireshark?

I already tried it but I could not see what the received package actually do. How did you reverse engineer that? Guessing? Trial&Error?

Could a wrong sent code probably destroy the cs500?
